load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "taste_writer",
    srcs = ["writer.go"],
    importpath = "github.com/yanicksenn/TasteLang/go/taste_writer",
    deps = [
        "//go/shared"
    ],
    visibility = ["//visibility:public"],
)
