load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "shared",
    srcs = ["shared.go"],
    importpath = "github.com/yanicksenn/TasteLang/go/shared",
    visibility = ["//visibility:public"],
)
