load("@rules_go//go:def.bzl", "go_test")

go_test(
    name = "taste_tokenizer",
    srcs = ["tokenizer_test.go"],
    deps = [
        "//go/shared",
	"//go/taste_tokenizer"
    ],
    visibility = ["//visibility:private"],
)
