load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "taste_parser",
    srcs = ["parser.go"],
    importpath = "github.com/yanicksenn/TasteLang/go/taste_parser",
    deps = [
        "//go/shared"
    ],
    visibility = ["//visibility:public"],
)
