load("@rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "main",
    srcs = ["main.go"],
    deps = [
	"//go/shared",
	"//go/taste_parser",
    	"//go/taste_tokenizer",
    	"//go/taste_writer"
    ]

)
